server:
  port: 8080
spring:
  application:
    name: microservice-simple-config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址，用于存放配置文件
          uri: https://github.com/caojx-git/spring-cloud-config-repo.git
          # Git仓库账号
          username:
          # Git仓库密码
          password:
