server:
  port: 8010

spring:
  application:
    name: microservice-simple-consumer-movie-feign-config-properties #应用名

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/  #eureka服务注册地址
  instance:
    prefer-ip-address: true

#要想用属性配置方式来达到上面Java代码方式的效果，只需在application.yml 中添加如下内容即可：
feign:
  client:
    config:
      microservice-simple-provider-user:
        loggerLevel: full

management:
  endpoint:
    health:
      show-details: always # 是否展示健康检查详情