server:
  port: 8761

eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      #添加security安全配置之后 http://{user}:{password}@EUREKA_HOST:EUREKA_PORT/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/

spring:
  application:
    name: microservice-simple-discovery-eureka
  security:
    user:
      name: user            # 配置登录的账号是user
      password: password123 # 配置登录的密码是password123

