server:
  port: 8031

spring:
  application:
    name: microservice-simple-hystrix-turbine

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

turbine:
  # 要监控的微服务列表，多个用,分隔
  appConfig: microservice-simple-consumer-movie,microservice-simple-consumer-movie-feign
  clusterNameExpression: "'default'"